# This workflow builds and verifies the EntroPy Password Generator project with multiple Python versions.
# It ensures compatibility, performs linting, and validates basic functionality.

name: EntroPy Password Generator CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.10", "3.12" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install linting tool
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        # Check for syntax errors, undefined names, and code style issues
        flake8 . --count --max-complexity=10 --max-line-length=127 --show-source --statistics

    - name: Debug working directory
      run: |
        # Print current directory and list files for debugging
        pwd
        ls -R

    - name: Verify script execution
      run: |
        # Verify that the main script runs without errors
        python -m entropy_password_generator.password_generator --length 15
