name: EntroPy Password Generator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Debug - Show commit and file content
      run: |
        echo "Current commit:"
        git log -1
        echo "Content of password_generator.py:"
        cat entropy_password_generator/password_generator.py

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 entropy_password_generator/password_generator.py --max-line-length=79 --ignore=E203,E305,W294 --count --show-source --statistics

    - name: Install package locally
      run: |
        pip install .

    - name: Run script with different modes
      run: |
        entropy-password-generator --mode 1
        entropy-password-generator --mode 12
        entropy-password-generator --mode 15
        entropy-password-generator --length 128
        entropy-password-generator --length 15 --no-special

    - name: Validate script output
      run: |
        entropy-password-generator --mode 1 | grep -q "Password:" && echo "Mode 1 output valid" || echo "Mode 1 output invalid"
        entropy-password-generator --mode 12 | grep -q "Password:" && echo "Mode 12 output valid" || echo "Mode 12 output invalid"
        entropy-password-generator --mode 15 | grep -q "Password:" && echo "Mode 15 output valid" || echo "Mode 15 output invalid"
